spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:multitenant_db}?currentSchema=${DB_SCHEMA:multitenant_schema}
    username: hieunp
    password: Abc@1234
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            batch_size: 1000
          order_inserts: true
          order_updates: true
          generate_statistics: false
      show-sql: true
      open-in-view: false

server:
  servlet:
    context-path: '/demo'
  port: 8081